#!/bin/bash
# clean.sh -- Remove compiled classes, generated parser files, and stray build artifacts.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

cd "$PROJECT_ROOT"

echo "Cleaning build artifacts..."

# Remove compiled class directories
if [ -d "lovelace" ]; then
    rm -rf lovelace
    echo "  Removed lovelace/"
fi

if [ -d "ast" ]; then
    rm -rf ast
    echo "  Removed ast/"
fi

# Remove JavaCC-generated parser files
GENERATED_FILES=(
    "src/lovelace/LovelaceParser.java"
    "src/lovelace/LovelaceParserConstants.java"
    "src/lovelace/LovelaceParserTokenManager.java"
    "src/lovelace/Token.java"
    "src/lovelace/TokenMgrError.java"
    "src/lovelace/ParseException.java"
    "src/lovelace/SimpleCharStream.java"
)

for f in "${GENERATED_FILES[@]}"; do
    if [ -f "$f" ]; then
        rm -f "$f"
        echo "  Removed $f"
    fi
done

# Remove stray .c files generated by the compiler in test/examples/
STRAY_C=$(find test/examples -name "*.c" 2>/dev/null)
if [ -n "$STRAY_C" ]; then
    echo "$STRAY_C" | while read -r f; do
        rm -f "$f"
        echo "  Removed $f"
    done
fi

echo ""
echo "Clean complete."
